//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/AutoreleasePool.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AutoreleasePool")
#ifdef RESTRICT_AutoreleasePool
#define INCLUDE_ALL_AutoreleasePool 0
#else
#define INCLUDE_ALL_AutoreleasePool 1
#endif
#undef RESTRICT_AutoreleasePool

#if !defined (GoogleJ2objcAnnotationsAutoreleasePool_) && (INCLUDE_ALL_AutoreleasePool || defined(INCLUDE_GoogleJ2objcAnnotationsAutoreleasePool))
#define GoogleJ2objcAnnotationsAutoreleasePool_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleJ2objcAnnotationsAutoreleasePool < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleJ2objcAnnotationsAutoreleasePool)

J2OBJC_TYPE_LITERAL_HEADER(GoogleJ2objcAnnotationsAutoreleasePool)

#endif

#pragma pop_macro("INCLUDE_ALL_AutoreleasePool")
