//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/BackgroundSchedulerWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BackgroundSchedulerWrapper")
#ifdef RESTRICT_BackgroundSchedulerWrapper
#define INCLUDE_ALL_BackgroundSchedulerWrapper 0
#else
#define INCLUDE_ALL_BackgroundSchedulerWrapper 1
#endif
#undef RESTRICT_BackgroundSchedulerWrapper

#if !defined (RuKorincRuntimeRxBackgroundSchedulerWrapper_) && (INCLUDE_ALL_BackgroundSchedulerWrapper || defined(INCLUDE_RuKorincRuntimeRxBackgroundSchedulerWrapper))
#define RuKorincRuntimeRxBackgroundSchedulerWrapper_

@protocol RuKorincRuntimeRxBackgroundSchedulerWrapper < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxBackgroundSchedulerWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxBackgroundSchedulerWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_BackgroundSchedulerWrapper")
