//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/BackgroundSchedulerWrapper.java
//

#include "BackgroundSchedulerWrapper.h"
#include "J2ObjC_source.h"

@interface RuKorincRuntimeRxBackgroundSchedulerWrapper : NSObject

@end

@implementation RuKorincRuntimeRxBackgroundSchedulerWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _RuKorincRuntimeRxBackgroundSchedulerWrapper = { "BackgroundSchedulerWrapper", "ru.korinc.runtime.rx", NULL, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeRxBackgroundSchedulerWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxBackgroundSchedulerWrapper)
