//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/subject/BSWrapper.java
//

#include "BSWrapper.h"
#include "J2ObjC_source.h"

@interface RuKorincRuntimeRxSubjectBSWrapper : NSObject

@end

@implementation RuKorincRuntimeRxSubjectBSWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSObject;", 0x401, -1, -1, -1, 0, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getValue);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "()TT;", "<T:Ljava/lang/Object;>Ljava/lang/Object;Lru/korinc/runtime/rx/subject/SubjectWrapper<TT;>;" };
  static const J2ObjcClassInfo _RuKorincRuntimeRxSubjectBSWrapper = { "BSWrapper", "ru.korinc.runtime.rx.subject", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 1, -1 };
  return &_RuKorincRuntimeRxSubjectBSWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxSubjectBSWrapper)
