//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/subject/BSWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BSWrapper")
#ifdef RESTRICT_BSWrapper
#define INCLUDE_ALL_BSWrapper 0
#else
#define INCLUDE_ALL_BSWrapper 1
#endif
#undef RESTRICT_BSWrapper

#if !defined (RuKorincRuntimeRxSubjectBSWrapper_) && (INCLUDE_ALL_BSWrapper || defined(INCLUDE_RuKorincRuntimeRxSubjectBSWrapper))
#define RuKorincRuntimeRxSubjectBSWrapper_

#define RESTRICT_SubjectWrapper 1
#define INCLUDE_RuKorincRuntimeRxSubjectSubjectWrapper 1
#include "SubjectWrapper.h"

@protocol RuKorincRuntimeRxSubjectBSWrapper < RuKorincRuntimeRxSubjectSubjectWrapper, JavaObject >

- (id)getValue;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxSubjectBSWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxSubjectBSWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_BSWrapper")
