//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/Consumer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Consumer")
#ifdef RESTRICT_Consumer
#define INCLUDE_ALL_Consumer 0
#else
#define INCLUDE_ALL_Consumer 1
#endif
#undef RESTRICT_Consumer

#if !defined (RuKorincRuntimeRxConsumer_) && (INCLUDE_ALL_Consumer || defined(INCLUDE_RuKorincRuntimeRxConsumer))
#define RuKorincRuntimeRxConsumer_

@protocol RuKorincRuntimeRxConsumer < JavaObject >

- (void)acceptWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxConsumer)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxConsumer)

#endif

#pragma pop_macro("INCLUDE_ALL_Consumer")
