//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/DisposableWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DisposableWrapper")
#ifdef RESTRICT_DisposableWrapper
#define INCLUDE_ALL_DisposableWrapper 0
#else
#define INCLUDE_ALL_DisposableWrapper 1
#endif
#undef RESTRICT_DisposableWrapper

#if !defined (RuKorincRuntimeRxDisposableWrapper_) && (INCLUDE_ALL_DisposableWrapper || defined(INCLUDE_RuKorincRuntimeRxDisposableWrapper))
#define RuKorincRuntimeRxDisposableWrapper_

@protocol RuKorincRuntimeRxDisposableWrapper < JavaObject >

- (void)dispose;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxDisposableWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxDisposableWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_DisposableWrapper")
