//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/DisposableWrapper.java
//

#include "DisposableWrapper.h"
#include "J2ObjC_source.h"

@interface RuKorincRuntimeRxDisposableWrapper : NSObject

@end

@implementation RuKorincRuntimeRxDisposableWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(dispose);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _RuKorincRuntimeRxDisposableWrapper = { "DisposableWrapper", "ru.korinc.runtime.rx", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeRxDisposableWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxDisposableWrapper)
