//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/Emitter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Emitter")
#ifdef RESTRICT_Emitter
#define INCLUDE_ALL_Emitter 0
#else
#define INCLUDE_ALL_Emitter 1
#endif
#undef RESTRICT_Emitter

#if !defined (RuKorincRuntimeRxEmitter_) && (INCLUDE_ALL_Emitter || defined(INCLUDE_RuKorincRuntimeRxEmitter))
#define RuKorincRuntimeRxEmitter_

@class JavaLangThrowable;

@protocol RuKorincRuntimeRxEmitter < JavaObject >

- (void)onNextWithId:(id)value;

- (void)onErrorWithJavaLangThrowable:(JavaLangThrowable *)error;

- (void)onComplete;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxEmitter)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxEmitter)

#endif

#pragma pop_macro("INCLUDE_ALL_Emitter")
