//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/Foo.java
//

#include "Foo.h"
#include "J2ObjC_source.h"

@implementation RuKorincRuntimeFoo

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincRuntimeFoo_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)getFoo {
  return foo_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getFoo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "foo_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _RuKorincRuntimeFoo = { "Foo", "ru.korinc.runtime", NULL, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeFoo;
}

@end

void RuKorincRuntimeFoo_init(RuKorincRuntimeFoo *self) {
  NSObject_init(self);
  self->foo_ = 42;
}

RuKorincRuntimeFoo *new_RuKorincRuntimeFoo_init() {
  J2OBJC_NEW_IMPL(RuKorincRuntimeFoo, init)
}

RuKorincRuntimeFoo *create_RuKorincRuntimeFoo_init() {
  J2OBJC_CREATE_IMPL(RuKorincRuntimeFoo, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincRuntimeFoo)
