//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/Foo.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Foo")
#ifdef RESTRICT_Foo
#define INCLUDE_ALL_Foo 0
#else
#define INCLUDE_ALL_Foo 1
#endif
#undef RESTRICT_Foo

#if !defined (RuKorincRuntimeFoo_) && (INCLUDE_ALL_Foo || defined(INCLUDE_RuKorincRuntimeFoo))
#define RuKorincRuntimeFoo_

@interface RuKorincRuntimeFoo : NSObject {
 @public
  jint foo_;
}

#pragma mark Public

- (instancetype)init;

- (jint)getFoo;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeFoo)

FOUNDATION_EXPORT void RuKorincRuntimeFoo_init(RuKorincRuntimeFoo *self);

FOUNDATION_EXPORT RuKorincRuntimeFoo *new_RuKorincRuntimeFoo_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeFoo *create_RuKorincRuntimeFoo_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeFoo)

#endif

#pragma pop_macro("INCLUDE_ALL_Foo")
