//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/Foo2.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Foo2")
#ifdef RESTRICT_Foo2
#define INCLUDE_ALL_Foo2 0
#else
#define INCLUDE_ALL_Foo2 1
#endif
#undef RESTRICT_Foo2

#if !defined (RuKorincRuntimeFoo2_) && (INCLUDE_ALL_Foo2 || defined(INCLUDE_RuKorincRuntimeFoo2))
#define RuKorincRuntimeFoo2_

@interface RuKorincRuntimeFoo2 : NSObject {
 @public
  jint foo_;
}

#pragma mark Public

- (instancetype)init;

- (jint)getFoo;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeFoo2)

FOUNDATION_EXPORT void RuKorincRuntimeFoo2_init(RuKorincRuntimeFoo2 *self);

FOUNDATION_EXPORT RuKorincRuntimeFoo2 *new_RuKorincRuntimeFoo2_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeFoo2 *create_RuKorincRuntimeFoo2_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeFoo2)

#endif

#pragma pop_macro("INCLUDE_ALL_Foo2")
