//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/Foo2.java
//

#include "Foo2.h"
#include "J2ObjC_source.h"

@implementation RuKorincRuntimeFoo2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincRuntimeFoo2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (jint)getFoo {
  return foo_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getFoo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "foo_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const J2ObjcClassInfo _RuKorincRuntimeFoo2 = { "Foo2", "ru.korinc.runtime", NULL, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeFoo2;
}

@end

void RuKorincRuntimeFoo2_init(RuKorincRuntimeFoo2 *self) {
  NSObject_init(self);
  self->foo_ = 43;
}

RuKorincRuntimeFoo2 *new_RuKorincRuntimeFoo2_init() {
  J2OBJC_NEW_IMPL(RuKorincRuntimeFoo2, init)
}

RuKorincRuntimeFoo2 *create_RuKorincRuntimeFoo2_init() {
  J2OBJC_CREATE_IMPL(RuKorincRuntimeFoo2, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincRuntimeFoo2)
