//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/Function.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Function")
#ifdef RESTRICT_Function
#define INCLUDE_ALL_Function 0
#else
#define INCLUDE_ALL_Function 1
#endif
#undef RESTRICT_Function

#if !defined (RuKorincRuntimeRxFunction_) && (INCLUDE_ALL_Function || defined(INCLUDE_RuKorincRuntimeRxFunction))
#define RuKorincRuntimeRxFunction_

@protocol RuKorincRuntimeRxFunction < JavaObject >

- (id)applyWithId:(id)t;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxFunction)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxFunction)

#endif

#pragma pop_macro("INCLUDE_ALL_Function")
