//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/common/annotations/GwtCompatible.java
//

#include "GwtCompatible.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/Documented.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@interface GoogleCommonAnnotationsGwtCompatible : NSObject

@end

__attribute__((unused)) static IOSObjectArray *GoogleCommonAnnotationsGwtCompatible__Annotations$0();

@implementation GoogleCommonAnnotationsGwtCompatible

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(serializable);
  methods[1].selector = @selector(emulated);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&GoogleCommonAnnotationsGwtCompatible__Annotations$0 };
  static const J2ObjcClassInfo _GoogleCommonAnnotationsGwtCompatible = { "GwtCompatible", "google.common.annotations", ptrTable, methods, NULL, 7, 0x2609, 2, 0, -1, -1, -1, -1, 0 };
  return &_GoogleCommonAnnotationsGwtCompatible;
}

@end

IOSObjectArray *GoogleCommonAnnotationsGwtCompatible__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, CLASS)), create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, TYPE), JreLoadEnum(JavaLangAnnotationElementType, METHOD) } count:2 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationDocumented() } count:3 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GoogleCommonAnnotationsGwtCompatible)
