//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/common/annotations/GwtCompatible.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GwtCompatible")
#ifdef RESTRICT_GwtCompatible
#define INCLUDE_ALL_GwtCompatible 0
#else
#define INCLUDE_ALL_GwtCompatible 1
#endif
#undef RESTRICT_GwtCompatible

#if !defined (GoogleCommonAnnotationsGwtCompatible_) && (INCLUDE_ALL_GwtCompatible || defined(INCLUDE_GoogleCommonAnnotationsGwtCompatible))
#define GoogleCommonAnnotationsGwtCompatible_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleCommonAnnotationsGwtCompatible < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleCommonAnnotationsGwtCompatible)

J2OBJC_TYPE_LITERAL_HEADER(GoogleCommonAnnotationsGwtCompatible)

#endif

#pragma pop_macro("INCLUDE_ALL_GwtCompatible")
