//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/common/annotations/GwtIncompatible.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GwtIncompatible")
#ifdef RESTRICT_GwtIncompatible
#define INCLUDE_ALL_GwtIncompatible 0
#else
#define INCLUDE_ALL_GwtIncompatible 1
#endif
#undef RESTRICT_GwtIncompatible

#if !defined (GoogleCommonAnnotationsGwtIncompatible_) && (INCLUDE_ALL_GwtIncompatible || defined(INCLUDE_GoogleCommonAnnotationsGwtIncompatible))
#define GoogleCommonAnnotationsGwtIncompatible_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleCommonAnnotationsGwtIncompatible < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleCommonAnnotationsGwtIncompatible)

J2OBJC_TYPE_LITERAL_HEADER(GoogleCommonAnnotationsGwtIncompatible)

#endif

#pragma pop_macro("INCLUDE_ALL_GwtIncompatible")
