//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/network/HttpProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HttpProvider")
#ifdef RESTRICT_HttpProvider
#define INCLUDE_ALL_HttpProvider 0
#else
#define INCLUDE_ALL_HttpProvider 1
#endif
#undef RESTRICT_HttpProvider

#if !defined (RuKorincRuntimeNetworkHttpProvider_) && (INCLUDE_ALL_HttpProvider || defined(INCLUDE_RuKorincRuntimeNetworkHttpProvider))
#define RuKorincRuntimeNetworkHttpProvider_

@protocol RuKorincRuntimeNetworkHttpExecutor;

@protocol RuKorincRuntimeNetworkHttpProvider < JavaObject >

- (id<RuKorincRuntimeNetworkHttpExecutor>)getExecutor;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeNetworkHttpProvider)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeNetworkHttpProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_HttpProvider")
