//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/network/HttpProvider.java
//

#include "HttpProvider.h"
#include "J2ObjC_source.h"

@interface RuKorincRuntimeNetworkHttpProvider : NSObject

@end

@implementation RuKorincRuntimeNetworkHttpProvider

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LRuKorincRuntimeNetworkHttpExecutor;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getExecutor);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _RuKorincRuntimeNetworkHttpProvider = { "HttpProvider", "ru.korinc.runtime.network", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeNetworkHttpProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeNetworkHttpProvider)
