//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/network/HttpCallback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HttpCallback")
#ifdef RESTRICT_HttpCallback
#define INCLUDE_ALL_HttpCallback 0
#else
#define INCLUDE_ALL_HttpCallback 1
#endif
#undef RESTRICT_HttpCallback

#if !defined (RuKorincRuntimeNetworkHttpCallback_) && (INCLUDE_ALL_HttpCallback || defined(INCLUDE_RuKorincRuntimeNetworkHttpCallback))
#define RuKorincRuntimeNetworkHttpCallback_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class JavaLangThrowable;
@class RuKorincRuntimeNetworkHttpResponse;

@interface RuKorincRuntimeNetworkHttpCallback : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (void)onFailureWithJavaLangThrowable:(JavaLangThrowable *)throwable;

- (void)onResponceWithRuKorincRuntimeNetworkHttpResponse:(RuKorincRuntimeNetworkHttpResponse *)response;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeNetworkHttpCallback)

FOUNDATION_EXPORT void RuKorincRuntimeNetworkHttpCallback_init(RuKorincRuntimeNetworkHttpCallback *self);

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpCallback *new_RuKorincRuntimeNetworkHttpCallback_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpCallback *create_RuKorincRuntimeNetworkHttpCallback_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeNetworkHttpCallback)

#endif

#pragma pop_macro("INCLUDE_ALL_HttpCallback")
