//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/network/HttpEx.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HttpEx")
#ifdef RESTRICT_HttpEx
#define INCLUDE_ALL_HttpEx 0
#else
#define INCLUDE_ALL_HttpEx 1
#endif
#undef RESTRICT_HttpEx

#if !defined (RuKorincRuntimeNetworkHttpEx_) && (INCLUDE_ALL_HttpEx || defined(INCLUDE_RuKorincRuntimeNetworkHttpEx))
#define RuKorincRuntimeNetworkHttpEx_

@class IOSObjectArray;

@protocol RuKorincRuntimeNetworkHttpEx < JavaObject >

- (NSString *)getWithNSString:(NSString *)url;

- (NSString *)putWithNSString:(NSString *)url
        withJavaLangByteArray:(IOSObjectArray *)contents;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeNetworkHttpEx)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeNetworkHttpEx)

#endif

#pragma pop_macro("INCLUDE_ALL_HttpEx")
