//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/network/HttpResponse.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_HttpResponse")
#ifdef RESTRICT_HttpResponse
#define INCLUDE_ALL_HttpResponse 0
#else
#define INCLUDE_ALL_HttpResponse 1
#endif
#undef RESTRICT_HttpResponse

#if !defined (RuKorincRuntimeNetworkHttpResponse_) && (INCLUDE_ALL_HttpResponse || defined(INCLUDE_RuKorincRuntimeNetworkHttpResponse))
#define RuKorincRuntimeNetworkHttpResponse_

@class IOSObjectArray;

@interface RuKorincRuntimeNetworkHttpResponse : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)code
               withNSString:(NSString *)content
               withNSString:(NSString *)url;

- (instancetype)initWithInt:(jint)code
               withNSString:(NSString *)content
               withNSString:(NSString *)url
          withNSStringArray:(IOSObjectArray *)headers;

- (jboolean)filter;

- (jint)getCode;

- (NSString *)getContent;

- (IOSObjectArray *)getHeaders;

- (NSString *)getUrl;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeNetworkHttpResponse)

FOUNDATION_EXPORT void RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_withNSStringArray_(RuKorincRuntimeNetworkHttpResponse *self, jint code, NSString *content, NSString *url, IOSObjectArray *headers);

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpResponse *new_RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_withNSStringArray_(jint code, NSString *content, NSString *url, IOSObjectArray *headers) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpResponse *create_RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_withNSStringArray_(jint code, NSString *content, NSString *url, IOSObjectArray *headers);

FOUNDATION_EXPORT void RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_(RuKorincRuntimeNetworkHttpResponse *self, jint code, NSString *content, NSString *url);

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpResponse *new_RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_(jint code, NSString *content, NSString *url) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeNetworkHttpResponse *create_RuKorincRuntimeNetworkHttpResponse_initWithInt_withNSString_withNSString_(jint code, NSString *content, NSString *url);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeNetworkHttpResponse)

#endif

#pragma pop_macro("INCLUDE_ALL_HttpResponse")
