//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/json/JsonArrayWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonArrayWrapper")
#ifdef RESTRICT_JsonArrayWrapper
#define INCLUDE_ALL_JsonArrayWrapper 0
#else
#define INCLUDE_ALL_JsonArrayWrapper 1
#endif
#undef RESTRICT_JsonArrayWrapper

#if !defined (RuKorincRuntimeJsonJsonArrayWrapper_) && (INCLUDE_ALL_JsonArrayWrapper || defined(INCLUDE_RuKorincRuntimeJsonJsonArrayWrapper))
#define RuKorincRuntimeJsonJsonArrayWrapper_

@protocol RuKorincRuntimeJsonJsonObjectWrapper;

@protocol RuKorincRuntimeJsonJsonArrayWrapper < JavaObject >

- (jint)length;

- (id<RuKorincRuntimeJsonJsonObjectWrapper>)getJsonObjectWrapperWithInt:(jint)position;

- (id<RuKorincRuntimeJsonJsonArrayWrapper>)getJsonArrayWrapperWithInt:(jint)position;

- (NSString *)getStringWithInt:(jint)position;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeJsonJsonArrayWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeJsonJsonArrayWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonArrayWrapper")
