//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/json/JsonObjectWrapper.java
//

#include "J2ObjC_source.h"
#include "JsonObjectWrapper.h"

@interface RuKorincRuntimeJsonJsonObjectWrapper : NSObject

@end

@implementation RuKorincRuntimeJsonJsonObjectWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LRuKorincRuntimeJsonJsonObjectWrapper;", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "LRuKorincRuntimeJsonJsonArrayWrapper;", 0x401, 3, 1, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 4, 1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 4, 5, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getJsonObjectWithNSString:);
  methods[1].selector = @selector(getJsonArrayWithNSString:);
  methods[2].selector = @selector(getStringWithNSString:);
  methods[3].selector = @selector(getStringWithNSString:withNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getJsonObject", "LNSString;", "LJavaLangNullPointerException;", "getJsonArray", "getString", "LNSString;LNSString;" };
  static const J2ObjcClassInfo _RuKorincRuntimeJsonJsonObjectWrapper = { "JsonObjectWrapper", "ru.korinc.runtime.json", ptrTable, methods, NULL, 7, 0x609, 4, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeJsonJsonObjectWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeJsonJsonObjectWrapper)
