//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/json/JsonProvider.java
//

#include "J2ObjC_source.h"
#include "JsonProvider.h"

@interface RuKorincRuntimeJsonJsonProvider : NSObject

@end

@implementation RuKorincRuntimeJsonJsonProvider

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LRuKorincRuntimeJsonJsonObjectWrapper;", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LRuKorincRuntimeJsonJsonArrayWrapper;", 0x401, 2, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getJsonWithNSString:);
  methods[1].selector = @selector(getJsonArrayWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getJson", "LNSString;", "getJsonArray" };
  static const J2ObjcClassInfo _RuKorincRuntimeJsonJsonProvider = { "JsonProvider", "ru.korinc.runtime.json", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeJsonJsonProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeJsonJsonProvider)
