//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/json/JsonObjectWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonObjectWrapper")
#ifdef RESTRICT_JsonObjectWrapper
#define INCLUDE_ALL_JsonObjectWrapper 0
#else
#define INCLUDE_ALL_JsonObjectWrapper 1
#endif
#undef RESTRICT_JsonObjectWrapper

#if !defined (RuKorincRuntimeJsonJsonObjectWrapper_) && (INCLUDE_ALL_JsonObjectWrapper || defined(INCLUDE_RuKorincRuntimeJsonJsonObjectWrapper))
#define RuKorincRuntimeJsonJsonObjectWrapper_

@protocol RuKorincRuntimeJsonJsonArrayWrapper;

@protocol RuKorincRuntimeJsonJsonObjectWrapper < JavaObject >

- (id<RuKorincRuntimeJsonJsonObjectWrapper>)getJsonObjectWithNSString:(NSString *)key;

- (id<RuKorincRuntimeJsonJsonArrayWrapper>)getJsonArrayWithNSString:(NSString *)key;

- (NSString *)getStringWithNSString:(NSString *)key;

- (NSString *)getStringWithNSString:(NSString *)key
                       withNSString:(NSString *)defaultValue;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeJsonJsonObjectWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeJsonJsonObjectWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonObjectWrapper")
