//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/json/JsonProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JsonProvider")
#ifdef RESTRICT_JsonProvider
#define INCLUDE_ALL_JsonProvider 0
#else
#define INCLUDE_ALL_JsonProvider 1
#endif
#undef RESTRICT_JsonProvider

#if !defined (RuKorincRuntimeJsonJsonProvider_) && (INCLUDE_ALL_JsonProvider || defined(INCLUDE_RuKorincRuntimeJsonJsonProvider))
#define RuKorincRuntimeJsonJsonProvider_

@protocol RuKorincRuntimeJsonJsonArrayWrapper;
@protocol RuKorincRuntimeJsonJsonObjectWrapper;

@protocol RuKorincRuntimeJsonJsonProvider < JavaObject >

- (id<RuKorincRuntimeJsonJsonObjectWrapper>)getJsonWithNSString:(NSString *)source;

- (id<RuKorincRuntimeJsonJsonArrayWrapper>)getJsonArrayWithNSString:(NSString *)spurce;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeJsonJsonProvider)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeJsonJsonProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_JsonProvider")
