//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/Load.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Load")
#ifdef RESTRICT_Load
#define INCLUDE_ALL_Load 0
#else
#define INCLUDE_ALL_Load 1
#endif
#undef RESTRICT_Load

#if !defined (RuKorincCoreEntityLoad_) && (INCLUDE_ALL_Load || defined(INCLUDE_RuKorincCoreEntityLoad))
#define RuKorincCoreEntityLoad_

#define RESTRICT_SearchEntity 1
#define INCLUDE_RuKorincCoreEntitySearchEntity 1
#include "SearchEntity.h"

@class RuKorincCoreEntityQuery;

@interface RuKorincCoreEntityLoad : RuKorincCoreEntitySearchEntity

#pragma mark Public

- (instancetype)initWithRuKorincCoreEntityQuery:(RuKorincCoreEntityQuery *)query;

- (RuKorincCoreEntityQuery *)getQuery;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreEntityLoad)

FOUNDATION_EXPORT void RuKorincCoreEntityLoad_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityLoad *self, RuKorincCoreEntityQuery *query);

FOUNDATION_EXPORT RuKorincCoreEntityLoad *new_RuKorincCoreEntityLoad_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreEntityLoad *create_RuKorincCoreEntityLoad_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreEntityLoad)

#endif

#pragma pop_macro("INCLUDE_ALL_Load")
