//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/logging/LogProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_LogProvider")
#ifdef RESTRICT_LogProvider
#define INCLUDE_ALL_LogProvider 0
#else
#define INCLUDE_ALL_LogProvider 1
#endif
#undef RESTRICT_LogProvider

#if !defined (RuKorincRuntimeLoggingLogProvider_) && (INCLUDE_ALL_LogProvider || defined(INCLUDE_RuKorincRuntimeLoggingLogProvider))
#define RuKorincRuntimeLoggingLogProvider_

@protocol RuKorincRuntimeLoggingLogProvider < JavaObject >

- (void)dWithNSString:(NSString *)tag
         withNSString:(NSString *)msg;

- (void)eWithNSException:(NSException *)throwable;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeLoggingLogProvider)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeLoggingLogProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_LogProvider")
