//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/logging/LogProvider.java
//

#include "J2ObjC_source.h"
#include "LogProvider.h"

@interface RuKorincRuntimeLoggingLogProvider : NSObject

@end

@implementation RuKorincRuntimeLoggingLogProvider

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(dWithNSString:withNSString:);
  methods[1].selector = @selector(eWithJavaLangThrowable:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "d", "LNSString;LNSString;", "e", "LJavaLangThrowable;" };
  static const J2ObjcClassInfo _RuKorincRuntimeLoggingLogProvider = { "LogProvider", "ru.korinc.runtime.logging", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeLoggingLogProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeLoggingLogProvider)
