//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/Model.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Model")
#ifdef RESTRICT_Model
#define INCLUDE_ALL_Model 0
#else
#define INCLUDE_ALL_Model 1
#endif
#undef RESTRICT_Model

#if !defined (RuKorincModel_) && (INCLUDE_ALL_Model || defined(INCLUDE_RuKorincModel))
#define RuKorincModel_

@class IOSObjectArray;
@class RuKorincRuntimeRuntimeConfiguration;
@protocol RuKorincRuntimeRxObservableWrapper;

@interface RuKorincModel : NSObject {
 @public
  IOSObjectArray *unitsMap_;
  IOSObjectArray *tensMap_;
}

#pragma mark Public

- (instancetype)initWithRuKorincRuntimeRuntimeConfiguration:(RuKorincRuntimeRuntimeConfiguration *)configuration;

- (void)countWithInt:(jint)i;

- (void)countInternalWithInt:(jint)i;

- (id<RuKorincRuntimeRxObservableWrapper>)getMultiplyEmitConverterWithNSString:(NSString *)s;

- (id<RuKorincRuntimeRxObservableWrapper>)subscribeCount;

#pragma mark Package-Private

- (NSString *)numberToWordsWithInt:(jint)number;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincModel)

J2OBJC_FIELD_SETTER(RuKorincModel, unitsMap_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(RuKorincModel, tensMap_, IOSObjectArray *)

FOUNDATION_EXPORT void RuKorincModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincModel *self, RuKorincRuntimeRuntimeConfiguration *configuration);

FOUNDATION_EXPORT RuKorincModel *new_RuKorincModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *configuration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincModel *create_RuKorincModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *configuration);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincModel)

#endif

#pragma pop_macro("INCLUDE_ALL_Model")
