//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/Model.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Model")
#ifdef RESTRICT_Model
#define INCLUDE_ALL_Model 0
#else
#define INCLUDE_ALL_Model 1
#endif
#undef RESTRICT_Model

#if !defined (RuKorincCoreModel_) && (INCLUDE_ALL_Model || defined(INCLUDE_RuKorincCoreModel))
#define RuKorincCoreModel_

@class RuKorincRuntimeRuntimeConfiguration;
@protocol RuKorincRuntimeRxObservableWrapper;

@interface RuKorincCoreModel : NSObject

#pragma mark Public

- (instancetype)initWithRuKorincRuntimeRuntimeConfiguration:(RuKorincRuntimeRuntimeConfiguration *)configuration;

- (id<RuKorincRuntimeRxObservableWrapper>)getSearchResults;

- (void)searchMovieByTitleQueryWithNSString:(NSString *)query;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreModel)

FOUNDATION_EXPORT void RuKorincCoreModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincCoreModel *self, RuKorincRuntimeRuntimeConfiguration *configuration);

FOUNDATION_EXPORT RuKorincCoreModel *new_RuKorincCoreModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *configuration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreModel *create_RuKorincCoreModel_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *configuration);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreModel)

#endif

#pragma pop_macro("INCLUDE_ALL_Model")
