//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/ModulesContext.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ModulesContext")
#ifdef RESTRICT_ModulesContext
#define INCLUDE_ALL_ModulesContext 0
#else
#define INCLUDE_ALL_ModulesContext 1
#endif
#undef RESTRICT_ModulesContext

#if !defined (RuKorincCoreModulesModulesContext_) && (INCLUDE_ALL_ModulesContext || defined(INCLUDE_RuKorincCoreModulesModulesContext))
#define RuKorincCoreModulesModulesContext_

@class RuKorincCoreModulesPlayerModule;
@class RuKorincRuntimeRuntimeConfiguration;

@interface RuKorincCoreModulesModulesContext : NSObject {
 @public
  RuKorincCoreModulesPlayerModule *mPlayerModule_;
}

#pragma mark Public

- (instancetype)initWithRuKorincRuntimeRuntimeConfiguration:(RuKorincRuntimeRuntimeConfiguration *)runtimeConfiguration;

- (RuKorincCoreModulesPlayerModule *)getPlayerModule;

#pragma mark Protected

- (RuKorincRuntimeRuntimeConfiguration *)getRuntimeConfiguration;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreModulesModulesContext)

J2OBJC_FIELD_SETTER(RuKorincCoreModulesModulesContext, mPlayerModule_, RuKorincCoreModulesPlayerModule *)

FOUNDATION_EXPORT void RuKorincCoreModulesModulesContext_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincCoreModulesModulesContext *self, RuKorincRuntimeRuntimeConfiguration *runtimeConfiguration);

FOUNDATION_EXPORT RuKorincCoreModulesModulesContext *new_RuKorincCoreModulesModulesContext_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *runtimeConfiguration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreModulesModulesContext *create_RuKorincCoreModulesModulesContext_initWithRuKorincRuntimeRuntimeConfiguration_(RuKorincRuntimeRuntimeConfiguration *runtimeConfiguration);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreModulesModulesContext)

#endif

#pragma pop_macro("INCLUDE_ALL_ModulesContext")
