//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/ModuleBase.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ModuleBase")
#ifdef RESTRICT_ModuleBase
#define INCLUDE_ALL_ModuleBase 0
#else
#define INCLUDE_ALL_ModuleBase 1
#endif
#undef RESTRICT_ModuleBase

#if !defined (RuKorincCoreModulesModuleBase_) && (INCLUDE_ALL_ModuleBase || defined(INCLUDE_RuKorincCoreModulesModuleBase))
#define RuKorincCoreModulesModuleBase_

@class RuKorincCoreModulesModulesContext;
@protocol RuKorincRuntimeRxRxProvider;

@interface RuKorincCoreModulesModuleBase : NSObject {
 @public
  RuKorincCoreModulesModulesContext *mContext_;
  id<RuKorincRuntimeRxRxProvider> mRxProvider_;
}

#pragma mark Public

- (instancetype)initWithRuKorincCoreModulesModulesContext:(RuKorincCoreModulesModulesContext *)context;

- (RuKorincCoreModulesModulesContext *)getContext;

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreModulesModuleBase)

J2OBJC_FIELD_SETTER(RuKorincCoreModulesModuleBase, mContext_, RuKorincCoreModulesModulesContext *)
J2OBJC_FIELD_SETTER(RuKorincCoreModulesModuleBase, mRxProvider_, id<RuKorincRuntimeRxRxProvider>)

FOUNDATION_EXPORT void RuKorincCoreModulesModuleBase_initWithRuKorincCoreModulesModulesContext_(RuKorincCoreModulesModuleBase *self, RuKorincCoreModulesModulesContext *context);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreModulesModuleBase)

#endif

#pragma pop_macro("INCLUDE_ALL_ModuleBase")
