//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/Movie.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Movie")
#ifdef RESTRICT_Movie
#define INCLUDE_ALL_Movie 0
#else
#define INCLUDE_ALL_Movie 1
#endif
#undef RESTRICT_Movie

#if !defined (RuKorincCoreEntityMovie_) && (INCLUDE_ALL_Movie || defined(INCLUDE_RuKorincCoreEntityMovie))
#define RuKorincCoreEntityMovie_

#define RESTRICT_SearchEntity 1
#define INCLUDE_RuKorincCoreEntitySearchEntity 1
#include "SearchEntity.h"

@interface RuKorincCoreEntityMovie : RuKorincCoreEntitySearchEntity

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)title
                    withNSString:(NSString *)year;

- (NSString *)additionalInfo;

- (NSString *)getTitle;

- (RuKorincCoreEntityMovie *)setAdditionalInfoWithNSString:(NSString *)additionalInfo;

- (RuKorincCoreEntityMovie *)setTitleWithNSString:(NSString *)title;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreEntityMovie)

FOUNDATION_EXPORT void RuKorincCoreEntityMovie_initWithNSString_withNSString_(RuKorincCoreEntityMovie *self, NSString *title, NSString *year);

FOUNDATION_EXPORT RuKorincCoreEntityMovie *new_RuKorincCoreEntityMovie_initWithNSString_withNSString_(NSString *title, NSString *year) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreEntityMovie *create_RuKorincCoreEntityMovie_initWithNSString_withNSString_(NSString *title, NSString *year);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreEntityMovie)

#endif

#pragma pop_macro("INCLUDE_ALL_Movie")
