//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/Movie.java
//

#include "J2ObjC_source.h"
#include "Movie.h"
#include "SearchEntity.h"

@interface RuKorincCoreEntityMovie () {
 @public
  NSString *title_;
  NSString *additionalInfo_;
}

@end

J2OBJC_FIELD_SETTER(RuKorincCoreEntityMovie, title_, NSString *)
J2OBJC_FIELD_SETTER(RuKorincCoreEntityMovie, additionalInfo_, NSString *)

@implementation RuKorincCoreEntityMovie

- (instancetype)initWithNSString:(NSString *)title
                    withNSString:(NSString *)year {
  RuKorincCoreEntityMovie_initWithNSString_withNSString_(self, title, year);
  return self;
}

- (NSString *)getTitle {
  return title_;
}

- (NSString *)additionalInfo {
  return additionalInfo_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:withNSString:);
  methods[1].selector = @selector(getTitle);
  methods[2].selector = @selector(additionalInfo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "title_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "additionalInfo_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;LNSString;" };
  static const J2ObjcClassInfo _RuKorincCoreEntityMovie = { "Movie", "ru.korinc.core.entity", ptrTable, methods, fields, 7, 0x1, 3, 2, -1, -1, -1, -1, -1 };
  return &_RuKorincCoreEntityMovie;
}

@end

void RuKorincCoreEntityMovie_initWithNSString_withNSString_(RuKorincCoreEntityMovie *self, NSString *title, NSString *year) {
  RuKorincCoreEntitySearchEntity_init(self);
  self->title_ = title;
  self->additionalInfo_ = year;
}

RuKorincCoreEntityMovie *new_RuKorincCoreEntityMovie_initWithNSString_withNSString_(NSString *title, NSString *year) {
  J2OBJC_NEW_IMPL(RuKorincCoreEntityMovie, initWithNSString_withNSString_, title, year)
}

RuKorincCoreEntityMovie *create_RuKorincCoreEntityMovie_initWithNSString_withNSString_(NSString *title, NSString *year) {
  J2OBJC_CREATE_IMPL(RuKorincCoreEntityMovie, initWithNSString_withNSString_, title, year)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreEntityMovie)
