//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/ObjectiveCName.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "ObjectiveCName.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

__attribute__((unused)) static IOSObjectArray *GoogleJ2objcAnnotationsObjectiveCName__Annotations$0();

@implementation GoogleJ2objcAnnotationsObjectiveCName

@synthesize value = value_;

- (IOSClass *)annotationType {
  return GoogleJ2objcAnnotationsObjectiveCName_class_();
}

- (NSString *)description {
  return @"@ObjectiveCName()";
}

- (void)dealloc {
  RELEASE_(value_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(value);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "value_", "LNSString;", .constantValue.asLong = 0, 0x1000, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { (void *)&GoogleJ2objcAnnotationsObjectiveCName__Annotations$0 };
  static const J2ObjcClassInfo _GoogleJ2objcAnnotationsObjectiveCName = { "ObjectiveCName", "google.j2objc.annotations", ptrTable, methods, fields, 7, 0x2609, 1, 1, -1, -1, -1, -1, 0 };
  return &_GoogleJ2objcAnnotationsObjectiveCName;
}

@end

id<GoogleJ2objcAnnotationsObjectiveCName> create_GoogleJ2objcAnnotationsObjectiveCName(NSString *value) {
  GoogleJ2objcAnnotationsObjectiveCName *self = AUTORELEASE([[GoogleJ2objcAnnotationsObjectiveCName alloc] init]);
  self->value_ = RETAIN_(value);
  return self;
}

IOSObjectArray *GoogleJ2objcAnnotationsObjectiveCName__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, TYPE), JreLoadEnum(JavaLangAnnotationElementType, METHOD), JreLoadEnum(JavaLangAnnotationElementType, CONSTRUCTOR), JreLoadEnum(JavaLangAnnotationElementType, PACKAGE) } count:4 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GoogleJ2objcAnnotationsObjectiveCName)
