//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/ObjectiveCName.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObjectiveCName")
#ifdef RESTRICT_ObjectiveCName
#define INCLUDE_ALL_ObjectiveCName 0
#else
#define INCLUDE_ALL_ObjectiveCName 1
#endif
#undef RESTRICT_ObjectiveCName

#if !defined (GoogleJ2objcAnnotationsObjectiveCName_) && (INCLUDE_ALL_ObjectiveCName || defined(INCLUDE_GoogleJ2objcAnnotationsObjectiveCName))
#define GoogleJ2objcAnnotationsObjectiveCName_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol GoogleJ2objcAnnotationsObjectiveCName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

@end

@interface GoogleJ2objcAnnotationsObjectiveCName : NSObject < GoogleJ2objcAnnotationsObjectiveCName > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleJ2objcAnnotationsObjectiveCName)

FOUNDATION_EXPORT id<GoogleJ2objcAnnotationsObjectiveCName> create_GoogleJ2objcAnnotationsObjectiveCName(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(GoogleJ2objcAnnotationsObjectiveCName)

#endif

#pragma pop_macro("INCLUDE_ALL_ObjectiveCName")
