//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/ObservableOnSubscribe.java
//

#include "J2ObjC_source.h"
#include "ObservableOnSubscribe.h"

@interface RuKorincRuntimeRxObservableOnSubscribe : NSObject

@end

@implementation RuKorincRuntimeRxObservableOnSubscribe

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, 2, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(subscribeWithRuKorincRuntimeRxEmitter:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "subscribe", "LRuKorincRuntimeRxEmitter;", "LJavaLangException;", "(Lru/korinc/runtime/rx/Emitter<TT;>;)V", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _RuKorincRuntimeRxObservableOnSubscribe = { "ObservableOnSubscribe", "ru.korinc.runtime.rx", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, 4, -1 };
  return &_RuKorincRuntimeRxObservableOnSubscribe;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxObservableOnSubscribe)
