//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/ObservableOnSubscribe.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObservableOnSubscribe")
#ifdef RESTRICT_ObservableOnSubscribe
#define INCLUDE_ALL_ObservableOnSubscribe 0
#else
#define INCLUDE_ALL_ObservableOnSubscribe 1
#endif
#undef RESTRICT_ObservableOnSubscribe

#if !defined (RuKorincRuntimeRxObservableOnSubscribe_) && (INCLUDE_ALL_ObservableOnSubscribe || defined(INCLUDE_RuKorincRuntimeRxObservableOnSubscribe))
#define RuKorincRuntimeRxObservableOnSubscribe_

@protocol RuKorincRuntimeRxEmitter;

@protocol RuKorincRuntimeRxObservableOnSubscribe < JavaObject >

- (void)subscribeWithRuKorincRuntimeRxEmitter:(id<RuKorincRuntimeRxEmitter>)e;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxObservableOnSubscribe)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxObservableOnSubscribe)

#endif

#pragma pop_macro("INCLUDE_ALL_ObservableOnSubscribe")
