//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/ObserverWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ObserverWrapper")
#ifdef RESTRICT_ObserverWrapper
#define INCLUDE_ALL_ObserverWrapper 0
#else
#define INCLUDE_ALL_ObserverWrapper 1
#endif
#undef RESTRICT_ObserverWrapper

#if !defined (RuKorincRuntimeRxObserverWrapper_) && (INCLUDE_ALL_ObserverWrapper || defined(INCLUDE_RuKorincRuntimeRxObserverWrapper))
#define RuKorincRuntimeRxObserverWrapper_

@class JavaLangThrowable;

@protocol RuKorincRuntimeRxObserverWrapper < JavaObject >

- (void)onNextWithId:(id)t;

- (void)onErrorWithJavaLangThrowable:(JavaLangThrowable *)e;

- (void)onComplete;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxObserverWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxObserverWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_ObserverWrapper")
