//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/PlayerModule.java
//

#include "J2ObjC_source.h"
#include "ModuleBase.h"
#include "ModulesContext.h"
#include "PlayerModule.h"

@implementation RuKorincCoreModulesPlayerModule

- (instancetype)initWithRuKorincCoreModulesModulesContext:(RuKorincCoreModulesModulesContext *)context {
  RuKorincCoreModulesPlayerModule_initWithRuKorincCoreModulesModulesContext_(self, context);
  return self;
}

- (void)run {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithRuKorincCoreModulesModulesContext:);
  methods[1].selector = @selector(run);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LRuKorincCoreModulesModulesContext;" };
  static const J2ObjcClassInfo _RuKorincCoreModulesPlayerModule = { "PlayerModule", "ru.korinc.core.modules", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincCoreModulesPlayerModule;
}

@end

void RuKorincCoreModulesPlayerModule_initWithRuKorincCoreModulesModulesContext_(RuKorincCoreModulesPlayerModule *self, RuKorincCoreModulesModulesContext *context) {
  RuKorincCoreModulesModuleBase_initWithRuKorincCoreModulesModulesContext_(self, context);
}

RuKorincCoreModulesPlayerModule *new_RuKorincCoreModulesPlayerModule_initWithRuKorincCoreModulesModulesContext_(RuKorincCoreModulesModulesContext *context) {
  J2OBJC_NEW_IMPL(RuKorincCoreModulesPlayerModule, initWithRuKorincCoreModulesModulesContext_, context)
}

RuKorincCoreModulesPlayerModule *create_RuKorincCoreModulesPlayerModule_initWithRuKorincCoreModulesModulesContext_(RuKorincCoreModulesModulesContext *context) {
  J2OBJC_CREATE_IMPL(RuKorincCoreModulesPlayerModule, initWithRuKorincCoreModulesModulesContext_, context)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreModulesPlayerModule)
