//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/player/PlayerActor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PlayerActor")
#ifdef RESTRICT_PlayerActor
#define INCLUDE_ALL_PlayerActor 0
#else
#define INCLUDE_ALL_PlayerActor 1
#endif
#undef RESTRICT_PlayerActor

#if !defined (RuKorincCoreModulesPlayerPlayerActor_) && (INCLUDE_ALL_PlayerActor || defined(INCLUDE_RuKorincCoreModulesPlayerPlayerActor))
#define RuKorincCoreModulesPlayerPlayerActor_

#define RESTRICT_RxActor 1
#define INCLUDE_RuKorincRuntimeRxRxActor 1
#include "RxActor.h"

@interface RuKorincCoreModulesPlayerPlayerActor : RuKorincRuntimeRxRxActor

#pragma mark Public

- (instancetype)init;

#pragma mark Protected

- (void)onMessageWithId:(id)message;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreModulesPlayerPlayerActor)

FOUNDATION_EXPORT void RuKorincCoreModulesPlayerPlayerActor_init(RuKorincCoreModulesPlayerPlayerActor *self);

FOUNDATION_EXPORT RuKorincCoreModulesPlayerPlayerActor *new_RuKorincCoreModulesPlayerPlayerActor_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreModulesPlayerPlayerActor *create_RuKorincCoreModulesPlayerPlayerActor_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreModulesPlayerPlayerActor)

#endif

#pragma pop_macro("INCLUDE_ALL_PlayerActor")
