//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/player/PlayerActor.java
//

#include "J2ObjC_source.h"
#include "PlayerActor.h"
#include "RxActor.h"

@implementation RuKorincCoreModulesPlayerPlayerActor

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincCoreModulesPlayerPlayerActor_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)onMessageWithId:(id)message {
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(onMessageWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onMessage", "LNSObject;" };
  static const J2ObjcClassInfo _RuKorincCoreModulesPlayerPlayerActor = { "PlayerActor", "ru.korinc.core.modules.player", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincCoreModulesPlayerPlayerActor;
}

@end

void RuKorincCoreModulesPlayerPlayerActor_init(RuKorincCoreModulesPlayerPlayerActor *self) {
  RuKorincRuntimeRxRxActor_init(self);
}

RuKorincCoreModulesPlayerPlayerActor *new_RuKorincCoreModulesPlayerPlayerActor_init() {
  J2OBJC_NEW_IMPL(RuKorincCoreModulesPlayerPlayerActor, init)
}

RuKorincCoreModulesPlayerPlayerActor *create_RuKorincCoreModulesPlayerPlayerActor_init() {
  J2OBJC_CREATE_IMPL(RuKorincCoreModulesPlayerPlayerActor, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreModulesPlayerPlayerActor)
