//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/Property.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Property")
#ifdef RESTRICT_Property
#define INCLUDE_ALL_Property 0
#else
#define INCLUDE_ALL_Property 1
#endif
#undef RESTRICT_Property

#if !defined (GoogleJ2objcAnnotationsProperty_) && (INCLUDE_ALL_Property || defined(INCLUDE_GoogleJ2objcAnnotationsProperty))
#define GoogleJ2objcAnnotationsProperty_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleJ2objcAnnotationsProperty < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleJ2objcAnnotationsProperty)

J2OBJC_TYPE_LITERAL_HEADER(GoogleJ2objcAnnotationsProperty)

#endif

#pragma pop_macro("INCLUDE_ALL_Property")
