//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/subject/PublishSubjectWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_PublishSubjectWrapper")
#ifdef RESTRICT_PublishSubjectWrapper
#define INCLUDE_ALL_PublishSubjectWrapper 0
#else
#define INCLUDE_ALL_PublishSubjectWrapper 1
#endif
#undef RESTRICT_PublishSubjectWrapper

#if !defined (RuKorincRuntimeRxSubjectPublishSubjectWrapper_) && (INCLUDE_ALL_PublishSubjectWrapper || defined(INCLUDE_RuKorincRuntimeRxSubjectPublishSubjectWrapper))
#define RuKorincRuntimeRxSubjectPublishSubjectWrapper_

#define RESTRICT_SubjectWrapper 1
#define INCLUDE_RuKorincRuntimeRxSubjectSubjectWrapper 1
#include "SubjectWrapper.h"

@protocol RuKorincRuntimeRxSubjectPublishSubjectWrapper < RuKorincRuntimeRxSubjectSubjectWrapper, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxSubjectPublishSubjectWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxSubjectPublishSubjectWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_PublishSubjectWrapper")
