//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/subject/PublishSubjectWrapper.java
//

#include "J2ObjC_source.h"
#include "PublishSubjectWrapper.h"

@interface RuKorincRuntimeRxSubjectPublishSubjectWrapper : NSObject

@end

@implementation RuKorincRuntimeRxSubjectPublishSubjectWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { "<T:Ljava/lang/Object;>Ljava/lang/Object;Lru/korinc/runtime/rx/subject/SubjectWrapper<TT;>;" };
  static const J2ObjcClassInfo _RuKorincRuntimeRxSubjectPublishSubjectWrapper = { "PublishSubjectWrapper", "ru.korinc.runtime.rx.subject", ptrTable, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, 0, -1 };
  return &_RuKorincRuntimeRxSubjectPublishSubjectWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxSubjectPublishSubjectWrapper)
