//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/QueryList.java
//

#include "J2ObjC_source.h"
#include "Query.h"
#include "QueryList.h"
#include "java/util/ArrayList.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface RuKorincCoreModulesQueryList () {
 @public
  RuKorincCoreEntityQuery *mQuery_;
}

@end

J2OBJC_FIELD_SETTER(RuKorincCoreModulesQueryList, mQuery_, RuKorincCoreEntityQuery *)

@implementation RuKorincCoreModulesQueryList

- (instancetype)initWithRuKorincCoreEntityQuery:(RuKorincCoreEntityQuery *)q {
  RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(self, q);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincCoreModulesQueryList_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (RuKorincCoreEntityQuery *)getQuery {
  return mQuery_;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LRuKorincCoreEntityQuery;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithRuKorincCoreEntityQuery:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(getQuery);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mQuery_", "LRuKorincCoreEntityQuery;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LRuKorincCoreEntityQuery;", "Ljava/util/ArrayList<Lru/korinc/core/entity/SearchEntity;>;" };
  static const J2ObjcClassInfo _RuKorincCoreModulesQueryList = { "QueryList", "ru.korinc.core.modules", ptrTable, methods, fields, 7, 0x1, 3, 1, -1, -1, -1, 1, -1 };
  return &_RuKorincCoreModulesQueryList;
}

@end

void RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreModulesQueryList *self, RuKorincCoreEntityQuery *q) {
  JavaUtilArrayList_init(self);
  self->mQuery_ = q;
}

RuKorincCoreModulesQueryList *new_RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *q) {
  J2OBJC_NEW_IMPL(RuKorincCoreModulesQueryList, initWithRuKorincCoreEntityQuery_, q)
}

RuKorincCoreModulesQueryList *create_RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *q) {
  J2OBJC_CREATE_IMPL(RuKorincCoreModulesQueryList, initWithRuKorincCoreEntityQuery_, q)
}

void RuKorincCoreModulesQueryList_init(RuKorincCoreModulesQueryList *self) {
  JavaUtilArrayList_init(self);
  self->mQuery_ = new_RuKorincCoreEntityQuery_init();
}

RuKorincCoreModulesQueryList *new_RuKorincCoreModulesQueryList_init() {
  J2OBJC_NEW_IMPL(RuKorincCoreModulesQueryList, init)
}

RuKorincCoreModulesQueryList *create_RuKorincCoreModulesQueryList_init() {
  J2OBJC_CREATE_IMPL(RuKorincCoreModulesQueryList, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreModulesQueryList)
