//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/modules/QueryList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_QueryList")
#ifdef RESTRICT_QueryList
#define INCLUDE_ALL_QueryList 0
#else
#define INCLUDE_ALL_QueryList 1
#endif
#undef RESTRICT_QueryList

#if !defined (RuKorincCoreModulesQueryList_) && (INCLUDE_ALL_QueryList || defined(INCLUDE_RuKorincCoreModulesQueryList))
#define RuKorincCoreModulesQueryList_

#define RESTRICT_JavaUtilArrayList 1
#define INCLUDE_JavaUtilArrayList 1
#include "java/util/ArrayList.h"

@class RuKorincCoreEntityQuery;
@class RuKorincCoreEntitySearchEntity;
@protocol JavaUtilCollection;

@interface RuKorincCoreModulesQueryList : JavaUtilArrayList

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithRuKorincCoreEntityQuery:(RuKorincCoreEntityQuery *)q;

- (RuKorincCoreEntityQuery *)getQuery;

- (RuKorincCoreEntitySearchEntity *)getWithInt:(jint)arg0;

- (RuKorincCoreEntitySearchEntity *)removeWithInt:(jint)arg0;

- (RuKorincCoreEntitySearchEntity *)setWithInt:(jint)arg0
                                        withId:(RuKorincCoreEntitySearchEntity *)arg1;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)initWithInt:(jint)arg0 NS_UNAVAILABLE;

- (instancetype)initWithJavaUtilCollection:(id<JavaUtilCollection>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreModulesQueryList)

FOUNDATION_EXPORT void RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreModulesQueryList *self, RuKorincCoreEntityQuery *q);

FOUNDATION_EXPORT RuKorincCoreModulesQueryList *new_RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *q) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreModulesQueryList *create_RuKorincCoreModulesQueryList_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *q);

FOUNDATION_EXPORT void RuKorincCoreModulesQueryList_init(RuKorincCoreModulesQueryList *self);

FOUNDATION_EXPORT RuKorincCoreModulesQueryList *new_RuKorincCoreModulesQueryList_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreModulesQueryList *create_RuKorincCoreModulesQueryList_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreModulesQueryList)

#endif

#pragma pop_macro("INCLUDE_ALL_QueryList")
