//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/Query.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Query")
#ifdef RESTRICT_Query
#define INCLUDE_ALL_Query 0
#else
#define INCLUDE_ALL_Query 1
#endif
#undef RESTRICT_Query

#if !defined (RuKorincCoreEntityQuery_) && (INCLUDE_ALL_Query || defined(INCLUDE_RuKorincCoreEntityQuery))
#define RuKorincCoreEntityQuery_

@class JavaUtilArrayList;

@interface RuKorincCoreEntityQuery : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)page
               withNSString:(NSString *)title;

- (JavaUtilArrayList *)getOldResults;

- (jint)getPage;

- (NSString *)getTitle;

- (RuKorincCoreEntityQuery *)setOldResultsWithJavaUtilArrayList:(JavaUtilArrayList *)oldResults;

- (RuKorincCoreEntityQuery *)setPageWithInt:(jint)page;

- (RuKorincCoreEntityQuery *)setTitleWithNSString:(NSString *)title;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreEntityQuery)

FOUNDATION_EXPORT void RuKorincCoreEntityQuery_initWithInt_withNSString_(RuKorincCoreEntityQuery *self, jint page, NSString *title);

FOUNDATION_EXPORT RuKorincCoreEntityQuery *new_RuKorincCoreEntityQuery_initWithInt_withNSString_(jint page, NSString *title) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreEntityQuery *create_RuKorincCoreEntityQuery_initWithInt_withNSString_(jint page, NSString *title);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreEntityQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_Query")
