//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/RetainedLocalRef.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RetainedLocalRef")
#ifdef RESTRICT_RetainedLocalRef
#define INCLUDE_ALL_RetainedLocalRef 0
#else
#define INCLUDE_ALL_RetainedLocalRef 1
#endif
#undef RESTRICT_RetainedLocalRef

#if !defined (GoogleJ2objcAnnotationsRetainedLocalRef_) && (INCLUDE_ALL_RetainedLocalRef || defined(INCLUDE_GoogleJ2objcAnnotationsRetainedLocalRef))
#define GoogleJ2objcAnnotationsRetainedLocalRef_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleJ2objcAnnotationsRetainedLocalRef < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleJ2objcAnnotationsRetainedLocalRef)

J2OBJC_TYPE_LITERAL_HEADER(GoogleJ2objcAnnotationsRetainedLocalRef)

#endif

#pragma pop_macro("INCLUDE_ALL_RetainedLocalRef")
