//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/RxActor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_RxActor")
#ifdef RESTRICT_RxActor
#define INCLUDE_ALL_RxActor 0
#else
#define INCLUDE_ALL_RxActor 1
#endif
#undef RESTRICT_RxActor

#if !defined (RuKorincRuntimeRxRxActor_) && (INCLUDE_ALL_RxActor || defined(INCLUDE_RuKorincRuntimeRxRxActor))
#define RuKorincRuntimeRxRxActor_

@class RuKorincRuntimeRxRxActor_ActorRef;

@interface RuKorincRuntimeRxRxActor : NSObject

#pragma mark Public

- (instancetype)init;

- (void)fireStart;

- (RuKorincRuntimeRxRxActor_ActorRef *)getRef;

#pragma mark Protected

- (void)onMessageWithId:(id)message;

- (void)onStart;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxRxActor)

FOUNDATION_EXPORT void RuKorincRuntimeRxRxActor_init(RuKorincRuntimeRxRxActor *self);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxRxActor)

#endif

#if !defined (RuKorincRuntimeRxRxActor_ActorRef_) && (INCLUDE_ALL_RxActor || defined(INCLUDE_RuKorincRuntimeRxRxActor_ActorRef))
#define RuKorincRuntimeRxRxActor_ActorRef_

@protocol RuKorincRuntimeRxSubjectPublishSubjectWrapper;

@interface RuKorincRuntimeRxRxActor_ActorRef : NSObject

#pragma mark Public

- (instancetype)init;

- (id<RuKorincRuntimeRxSubjectPublishSubjectWrapper>)getRef;

- (void)sendWithId:(id)message;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxRxActor_ActorRef)

FOUNDATION_EXPORT void RuKorincRuntimeRxRxActor_ActorRef_init(RuKorincRuntimeRxRxActor_ActorRef *self);

FOUNDATION_EXPORT RuKorincRuntimeRxRxActor_ActorRef *new_RuKorincRuntimeRxRxActor_ActorRef_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeRxRxActor_ActorRef *create_RuKorincRuntimeRxRxActor_ActorRef_init();

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxRxActor_ActorRef)

#endif

#pragma pop_macro("INCLUDE_ALL_RxActor")
