//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/SearchResults.java
//

#include "J2ObjC_source.h"
#include "Query.h"
#include "SearchResults.h"
#include "java/util/ArrayList.h"

#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface RuKorincCoreEntitySearchResults () {
 @public
  RuKorincCoreEntityQuery *mQuery_;
}

@end

J2OBJC_FIELD_SETTER(RuKorincCoreEntitySearchResults, mQuery_, RuKorincCoreEntityQuery *)

@implementation RuKorincCoreEntitySearchResults

- (instancetype)initWithRuKorincCoreEntityQuery:(RuKorincCoreEntityQuery *)query {
  RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(self, query);
  return self;
}

- (RuKorincCoreEntityQuery *)getQuery {
  return mQuery_;
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LRuKorincCoreEntityQuery;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithRuKorincCoreEntityQuery:);
  methods[1].selector = @selector(getQuery);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mQuery_", "LRuKorincCoreEntityQuery;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LRuKorincCoreEntityQuery;", "Ljava/util/ArrayList<Lru/korinc/core/entity/SearchEntity;>;" };
  static const J2ObjcClassInfo _RuKorincCoreEntitySearchResults = { "SearchResults", "ru.korinc.core.entity", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, 1, -1 };
  return &_RuKorincCoreEntitySearchResults;
}

@end

void RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntitySearchResults *self, RuKorincCoreEntityQuery *query) {
  JavaUtilArrayList_init(self);
  self->mQuery_ = query;
}

RuKorincCoreEntitySearchResults *new_RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query) {
  J2OBJC_NEW_IMPL(RuKorincCoreEntitySearchResults, initWithRuKorincCoreEntityQuery_, query)
}

RuKorincCoreEntitySearchResults *create_RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query) {
  J2OBJC_CREATE_IMPL(RuKorincCoreEntitySearchResults, initWithRuKorincCoreEntityQuery_, query)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreEntitySearchResults)
