//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/SearchEntity.java
//

#include "J2ObjC_source.h"
#include "SearchEntity.h"

@implementation RuKorincCoreEntitySearchEntity

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincCoreEntitySearchEntity_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _RuKorincCoreEntitySearchEntity = { "SearchEntity", "ru.korinc.core.entity", NULL, methods, NULL, 7, 0x401, 1, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincCoreEntitySearchEntity;
}

@end

void RuKorincCoreEntitySearchEntity_init(RuKorincCoreEntitySearchEntity *self) {
  NSObject_init(self);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincCoreEntitySearchEntity)
