//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/SearchEntity.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SearchEntity")
#ifdef RESTRICT_SearchEntity
#define INCLUDE_ALL_SearchEntity 0
#else
#define INCLUDE_ALL_SearchEntity 1
#endif
#undef RESTRICT_SearchEntity

#if !defined (RuKorincCoreEntitySearchEntity_) && (INCLUDE_ALL_SearchEntity || defined(INCLUDE_RuKorincCoreEntitySearchEntity))
#define RuKorincCoreEntitySearchEntity_

@interface RuKorincCoreEntitySearchEntity : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreEntitySearchEntity)

FOUNDATION_EXPORT void RuKorincCoreEntitySearchEntity_init(RuKorincCoreEntitySearchEntity *self);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreEntitySearchEntity)

#endif

#pragma pop_macro("INCLUDE_ALL_SearchEntity")
