//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/entity/SearchResults.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SearchResults")
#ifdef RESTRICT_SearchResults
#define INCLUDE_ALL_SearchResults 0
#else
#define INCLUDE_ALL_SearchResults 1
#endif
#undef RESTRICT_SearchResults

#if !defined (RuKorincCoreEntitySearchResults_) && (INCLUDE_ALL_SearchResults || defined(INCLUDE_RuKorincCoreEntitySearchResults))
#define RuKorincCoreEntitySearchResults_

#define RESTRICT_JavaUtilArrayList 1
#define INCLUDE_JavaUtilArrayList 1
#include "java/util/ArrayList.h"

@class RuKorincCoreEntityQuery;
@class RuKorincCoreEntitySearchEntity;

@interface RuKorincCoreEntitySearchResults : JavaUtilArrayList

#pragma mark Public

- (instancetype)initWithRuKorincCoreEntityQuery:(RuKorincCoreEntityQuery *)query;

- (RuKorincCoreEntityQuery *)getQuery;

- (RuKorincCoreEntitySearchEntity *)getWithInt:(jint)arg0;

- (RuKorincCoreEntitySearchEntity *)removeWithInt:(jint)arg0;

- (RuKorincCoreEntitySearchEntity *)setWithInt:(jint)arg0
                                        withId:(RuKorincCoreEntitySearchEntity *)arg1;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreEntitySearchResults)

FOUNDATION_EXPORT void RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntitySearchResults *self, RuKorincCoreEntityQuery *query);

FOUNDATION_EXPORT RuKorincCoreEntitySearchResults *new_RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreEntitySearchResults *create_RuKorincCoreEntitySearchResults_initWithRuKorincCoreEntityQuery_(RuKorincCoreEntityQuery *query);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreEntitySearchResults)

#endif

#pragma pop_macro("INCLUDE_ALL_SearchResults")
