//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/StringObservable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_StringObservable")
#ifdef RESTRICT_StringObservable
#define INCLUDE_ALL_StringObservable 0
#else
#define INCLUDE_ALL_StringObservable 1
#endif
#undef RESTRICT_StringObservable

#if !defined (RuKorincRuntimeRxStringObservable_) && (INCLUDE_ALL_StringObservable || defined(INCLUDE_RuKorincRuntimeRxStringObservable))
#define RuKorincRuntimeRxStringObservable_

#define RESTRICT_ObservableWrapper 1
#define INCLUDE_RuKorincRuntimeRxObservableWrapper 1
#include "ObservableWrapper.h"

@protocol RuKorincRuntimeRxBackgroundSchedulerWrapper;
@protocol RuKorincRuntimeRxConsumer;
@protocol RuKorincRuntimeRxDisposableWrapper;
@protocol RuKorincRuntimeRxFunction;

@interface RuKorincRuntimeRxStringObservable : NSObject < RuKorincRuntimeRxObservableWrapper >

#pragma mark Public

- (instancetype)initWithRuKorincRuntimeRxObservableWrapper:(id<RuKorincRuntimeRxObservableWrapper>)source;

- (id<RuKorincRuntimeRxObservableWrapper>)flatMapWithFunc:(id<RuKorincRuntimeRxFunction>)mapper;

+ (RuKorincRuntimeRxStringObservable *)fromWithRuKorincRuntimeRxObservableWrapper:(id<RuKorincRuntimeRxObservableWrapper>)source;

- (id<RuKorincRuntimeRxObservableWrapper>)getSource;

- (id<RuKorincRuntimeRxObservableWrapper>)mapWithFunc:(id<RuKorincRuntimeRxFunction>)func1;

- (id<RuKorincRuntimeRxObservableWrapper>)observeOnWithScheduler:(id<RuKorincRuntimeRxBackgroundSchedulerWrapper>)scheduler;

- (RuKorincRuntimeRxStringObservable *)observeOnMain;

- (id<RuKorincRuntimeRxDisposableWrapper>)subscribeWithConsumer:(id<RuKorincRuntimeRxConsumer>)consumer;

- (id<RuKorincRuntimeRxObservableWrapper>)subscribeOnWithScheduler:(id<RuKorincRuntimeRxBackgroundSchedulerWrapper>)scheduler;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxStringObservable)

FOUNDATION_EXPORT void RuKorincRuntimeRxStringObservable_initWithRuKorincRuntimeRxObservableWrapper_(RuKorincRuntimeRxStringObservable *self, id<RuKorincRuntimeRxObservableWrapper> source);

FOUNDATION_EXPORT RuKorincRuntimeRxStringObservable *new_RuKorincRuntimeRxStringObservable_initWithRuKorincRuntimeRxObservableWrapper_(id<RuKorincRuntimeRxObservableWrapper> source) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincRuntimeRxStringObservable *create_RuKorincRuntimeRxStringObservable_initWithRuKorincRuntimeRxObservableWrapper_(id<RuKorincRuntimeRxObservableWrapper> source);

FOUNDATION_EXPORT RuKorincRuntimeRxStringObservable *RuKorincRuntimeRxStringObservable_fromWithRuKorincRuntimeRxObservableWrapper_(id<RuKorincRuntimeRxObservableWrapper> source);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxStringObservable)

#endif

#pragma pop_macro("INCLUDE_ALL_StringObservable")
