//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/runtime/rx/subject/SubjectWrapper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SubjectWrapper")
#ifdef RESTRICT_SubjectWrapper
#define INCLUDE_ALL_SubjectWrapper 0
#else
#define INCLUDE_ALL_SubjectWrapper 1
#endif
#undef RESTRICT_SubjectWrapper

#if !defined (RuKorincRuntimeRxSubjectSubjectWrapper_) && (INCLUDE_ALL_SubjectWrapper || defined(INCLUDE_RuKorincRuntimeRxSubjectSubjectWrapper))
#define RuKorincRuntimeRxSubjectSubjectWrapper_

#define RESTRICT_ObservableWrapper 1
#define INCLUDE_RuKorincRuntimeRxObservableWrapper 1
#include "ObservableWrapper.h"

#define RESTRICT_ObserverWrapper 1
#define INCLUDE_RuKorincRuntimeRxObserverWrapper 1
#include "ObserverWrapper.h"

@protocol RuKorincRuntimeRxSubjectSubjectWrapper < RuKorincRuntimeRxObservableWrapper, RuKorincRuntimeRxObserverWrapper, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeRxSubjectSubjectWrapper)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeRxSubjectSubjectWrapper)

#endif

#pragma pop_macro("INCLUDE_ALL_SubjectWrapper")
