//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/rx/subject/SubjectWrapper.java
//

#include "J2ObjC_source.h"
#include "SubjectWrapper.h"

@interface RuKorincRuntimeRxSubjectSubjectWrapper : NSObject

@end

@implementation RuKorincRuntimeRxSubjectSubjectWrapper

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { "<T:Ljava/lang/Object;>Ljava/lang/Object;Lru/korinc/runtime/rx/ObservableWrapper<TT;>;Lru/korinc/runtime/rx/ObserverWrapper<TT;>;" };
  static const J2ObjcClassInfo _RuKorincRuntimeRxSubjectSubjectWrapper = { "SubjectWrapper", "ru.korinc.runtime.rx.subject", ptrTable, NULL, NULL, 7, 0x609, 0, 0, -1, -1, -1, 0, -1 };
  return &_RuKorincRuntimeRxSubjectSubjectWrapper;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeRxSubjectSubjectWrapper)
