//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/timeout/TimeoutProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TimeoutProvider")
#ifdef RESTRICT_TimeoutProvider
#define INCLUDE_ALL_TimeoutProvider 0
#else
#define INCLUDE_ALL_TimeoutProvider 1
#endif
#undef RESTRICT_TimeoutProvider

#if !defined (RuKorincRuntimeTimeoutTimeoutProvider_) && (INCLUDE_ALL_TimeoutProvider || defined(INCLUDE_RuKorincRuntimeTimeoutTimeoutProvider))
#define RuKorincRuntimeTimeoutTimeoutProvider_

@protocol RuKorincRuntimeTimeoutTimeoutProvider < JavaObject >

- (void)sleepWithInt:(jint)millis;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeTimeoutTimeoutProvider)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeTimeoutTimeoutProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_TimeoutProvider")
