//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/utils/Touple.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Touple")
#ifdef RESTRICT_Touple
#define INCLUDE_ALL_Touple 0
#else
#define INCLUDE_ALL_Touple 1
#endif
#undef RESTRICT_Touple

#if !defined (RuKorincUtilsTouple_) && (INCLUDE_ALL_Touple || defined(INCLUDE_RuKorincUtilsTouple))
#define RuKorincUtilsTouple_

@interface RuKorincUtilsTouple : NSObject

#pragma mark Public

- (instancetype)initWithId:(id)a
                    withId:(id)b;

- (jboolean)isEqual:(id)o;

- (id)getA;

- (id)getB;

- (NSUInteger)hash;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincUtilsTouple)

FOUNDATION_EXPORT void RuKorincUtilsTouple_initWithId_withId_(RuKorincUtilsTouple *self, id a, id b);

FOUNDATION_EXPORT RuKorincUtilsTouple *new_RuKorincUtilsTouple_initWithId_withId_(id a, id b) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincUtilsTouple *create_RuKorincUtilsTouple_initWithId_withId_(id a, id b);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincUtilsTouple)

#endif

#pragma pop_macro("INCLUDE_ALL_Touple")
