//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/utils/Touple.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Touple")
#ifdef RESTRICT_Touple
#define INCLUDE_ALL_Touple 0
#else
#define INCLUDE_ALL_Touple 1
#endif
#undef RESTRICT_Touple

#if !defined (RuKorincCoreUtilsTouple_) && (INCLUDE_ALL_Touple || defined(INCLUDE_RuKorincCoreUtilsTouple))
#define RuKorincCoreUtilsTouple_

@interface RuKorincCoreUtilsTouple : NSObject

#pragma mark Public

- (instancetype)initWithId:(id)a
                    withId:(id)b;

- (jboolean)isEqual:(id)o;

- (id)getA;

- (id)getB;

- (NSUInteger)hash;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsTouple)

FOUNDATION_EXPORT void RuKorincCoreUtilsTouple_initWithId_withId_(RuKorincCoreUtilsTouple *self, id a, id b);

FOUNDATION_EXPORT RuKorincCoreUtilsTouple *new_RuKorincCoreUtilsTouple_initWithId_withId_(id a, id b) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreUtilsTouple *create_RuKorincCoreUtilsTouple_initWithId_withId_(id a, id b);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsTouple)

#endif

#pragma pop_macro("INCLUDE_ALL_Touple")
