//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/utils/UrlEncoderProvider.java
//

#include "J2ObjC_source.h"
#include "UrlEncoderProvider.h"

@interface RuKorincRuntimeUtilsUrlEncoderProvider : NSObject

@end

@implementation RuKorincRuntimeUtilsUrlEncoderProvider

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(encodeQueryStringWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "encodeQueryString", "LNSString;" };
  static const J2ObjcClassInfo _RuKorincRuntimeUtilsUrlEncoderProvider = { "UrlEncoderProvider", "ru.korinc.runtime.utils", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_RuKorincRuntimeUtilsUrlEncoderProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincRuntimeUtilsUrlEncoderProvider)
