//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/utils/UrlEncoderProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UrlEncoderProvider")
#ifdef RESTRICT_UrlEncoderProvider
#define INCLUDE_ALL_UrlEncoderProvider 0
#else
#define INCLUDE_ALL_UrlEncoderProvider 1
#endif
#undef RESTRICT_UrlEncoderProvider

#if !defined (RuKorincRuntimeUtilsUrlEncoderProvider_) && (INCLUDE_ALL_UrlEncoderProvider || defined(INCLUDE_RuKorincRuntimeUtilsUrlEncoderProvider))
#define RuKorincRuntimeUtilsUrlEncoderProvider_

@protocol RuKorincRuntimeUtilsUrlEncoderProvider < JavaObject >

- (NSString *)encodeQueryStringWithNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeUtilsUrlEncoderProvider)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeUtilsUrlEncoderProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_UrlEncoderProvider")
