//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../runtime/src/main/java/ru/korinc/runtime/utils/UrlEncoder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_UrlEncoder")
#ifdef RESTRICT_UrlEncoder
#define INCLUDE_ALL_UrlEncoder 0
#else
#define INCLUDE_ALL_UrlEncoder 1
#endif
#undef RESTRICT_UrlEncoder

#if !defined (RuKorincRuntimeUtilsUrlEncoder_) && (INCLUDE_ALL_UrlEncoder || defined(INCLUDE_RuKorincRuntimeUtilsUrlEncoder))
#define RuKorincRuntimeUtilsUrlEncoder_

@protocol RuKorincRuntimeUtilsUrlEncoder < JavaObject >

- (NSString *)encodeQueryStringWithNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincRuntimeUtilsUrlEncoder)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincRuntimeUtilsUrlEncoder)

#endif

#pragma pop_macro("INCLUDE_ALL_UrlEncoder")
