//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/utils/Utils.java
//

#include "J2ObjC_source.h"
#include "Utils.h"
#include "java/lang/Iterable.h"
#include "java/util/ArrayList.h"
#include "java/util/Iterator.h"

@interface RuKorincUtilsUtils_SearchResult () {
 @public
  jint position_;
  id item_;
}

@end

J2OBJC_FIELD_SETTER(RuKorincUtilsUtils_SearchResult, item_, id)

@interface RuKorincUtilsUtils_Matcher : NSObject

@end

@interface RuKorincUtilsUtils_ApplySearchResult : NSObject

@end

@interface RuKorincUtilsUtils_Apply : NSObject

@end

@interface RuKorincUtilsUtils_Action : NSObject

@end

@implementation RuKorincUtilsUtils

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  RuKorincUtilsUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
   withRuKorincUtilsUtils_Matcher:(id<RuKorincUtilsUtils_Matcher>)matcher
     withRuKorincUtilsUtils_Apply:(id<RuKorincUtilsUtils_Apply>)action {
  RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(source, matcher, action);
}

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
     withRuKorincUtilsUtils_Apply:(id<RuKorincUtilsUtils_Apply>)action {
  RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Apply_(source, action);
}

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
   withRuKorincUtilsUtils_Matcher:(id<RuKorincUtilsUtils_Matcher>)matcher
   withRuKorincUtilsUtils_Matcher:(id<RuKorincUtilsUtils_Matcher>)breakOn
     withRuKorincUtilsUtils_Apply:(id<RuKorincUtilsUtils_Apply>)action {
  RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(source, matcher, breakOn, action);
}

+ (RuKorincUtilsUtils_SearchResult *)arrayListFirstWithJavaUtilArrayList:(JavaUtilArrayList *)source
                                          withRuKorincUtilsUtils_Matcher:(id<RuKorincUtilsUtils_Matcher>)condition
                                withRuKorincUtilsUtils_ApplySearchResult:(id<RuKorincUtilsUtils_ApplySearchResult>)ifFound {
  return RuKorincUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_ApplySearchResult_(source, condition, ifFound);
}

+ (RuKorincUtilsUtils_SearchResult *)arrayListFirstWithJavaUtilArrayList:(JavaUtilArrayList *)source
                                          withRuKorincUtilsUtils_Matcher:(id<RuKorincUtilsUtils_Matcher>)condition
                                withRuKorincUtilsUtils_ApplySearchResult:(id<RuKorincUtilsUtils_ApplySearchResult>)ifFound
                                           withRuKorincUtilsUtils_Action:(id<RuKorincUtilsUtils_Action>)not_ {
  return RuKorincUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_ApplySearchResult_withRuKorincUtilsUtils_Action_(source, condition, ifFound, not_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, -1, 2, -1, -1 },
    { NULL, "V", 0x9, 0, 3, -1, 4, -1, -1 },
    { NULL, "V", 0x9, 0, 5, -1, 6, -1, -1 },
    { NULL, "LRuKorincUtilsUtils_SearchResult;", 0x9, 7, 8, -1, 9, -1, -1 },
    { NULL, "LRuKorincUtilsUtils_SearchResult;", 0x9, 7, 10, -1, 11, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(applyWithJavaLangIterable:withRuKorincUtilsUtils_Matcher:withRuKorincUtilsUtils_Apply:);
  methods[2].selector = @selector(applyWithJavaLangIterable:withRuKorincUtilsUtils_Apply:);
  methods[3].selector = @selector(applyWithJavaLangIterable:withRuKorincUtilsUtils_Matcher:withRuKorincUtilsUtils_Matcher:withRuKorincUtilsUtils_Apply:);
  methods[4].selector = @selector(arrayListFirstWithJavaUtilArrayList:withRuKorincUtilsUtils_Matcher:withRuKorincUtilsUtils_ApplySearchResult:);
  methods[5].selector = @selector(arrayListFirstWithJavaUtilArrayList:withRuKorincUtilsUtils_Matcher:withRuKorincUtilsUtils_ApplySearchResult:withRuKorincUtilsUtils_Action:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "apply", "LJavaLangIterable;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_Apply;", "<T:Ljava/lang/Object;>(Ljava/lang/Iterable<TT;>;Lru/korinc/utils/Utils$Matcher<TT;>;Lru/korinc/utils/Utils$Apply<TT;>;)V", "LJavaLangIterable;LRuKorincUtilsUtils_Apply;", "<T:Ljava/lang/Object;>(Ljava/lang/Iterable<TT;>;Lru/korinc/utils/Utils$Apply<TT;>;)V", "LJavaLangIterable;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_Apply;", "<T:Ljava/lang/Object;>(Ljava/lang/Iterable<TT;>;Lru/korinc/utils/Utils$Matcher<TT;>;Lru/korinc/utils/Utils$Matcher<TT;>;Lru/korinc/utils/Utils$Apply<TT;>;)V", "arrayListFirst", "LJavaUtilArrayList;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_ApplySearchResult;", "<T:Ljava/lang/Object;>(Ljava/util/ArrayList<TT;>;Lru/korinc/utils/Utils$Matcher<TT;>;Lru/korinc/utils/Utils$ApplySearchResult<TT;>;)Lru/korinc/utils/Utils$SearchResult<TT;>;", "LJavaUtilArrayList;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_ApplySearchResult;LRuKorincUtilsUtils_Action;", "<T:Ljava/lang/Object;>(Ljava/util/ArrayList<TT;>;Lru/korinc/utils/Utils$Matcher<TT;>;Lru/korinc/utils/Utils$ApplySearchResult<TT;>;Lru/korinc/utils/Utils$Action;)Lru/korinc/utils/Utils$SearchResult<TT;>;", "LRuKorincUtilsUtils_SearchResult;LRuKorincUtilsUtils_Matcher;LRuKorincUtilsUtils_ApplySearchResult;LRuKorincUtilsUtils_Apply;LRuKorincUtilsUtils_Action;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils = { "Utils", "ru.korinc.utils", ptrTable, methods, NULL, 7, 0x1, 6, 0, -1, 12, -1, -1, -1 };
  return &_RuKorincUtilsUtils;
}

@end

void RuKorincUtilsUtils_init(RuKorincUtilsUtils *self) {
  NSObject_init(self);
}

RuKorincUtilsUtils *new_RuKorincUtilsUtils_init() {
  J2OBJC_NEW_IMPL(RuKorincUtilsUtils, init)
}

RuKorincUtilsUtils *create_RuKorincUtilsUtils_init() {
  J2OBJC_CREATE_IMPL(RuKorincUtilsUtils, init)
}

void RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincUtilsUtils_Matcher> matcher, id<RuKorincUtilsUtils_Apply> action) {
  RuKorincUtilsUtils_initialize();
  RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(source, matcher, nil, action);
}

void RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincUtilsUtils_Apply> action) {
  RuKorincUtilsUtils_initialize();
  RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(source, nil, nil, action);
}

void RuKorincUtilsUtils_applyWithJavaLangIterable_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincUtilsUtils_Matcher> matcher, id<RuKorincUtilsUtils_Matcher> breakOn, id<RuKorincUtilsUtils_Apply> action) {
  RuKorincUtilsUtils_initialize();
  for (id<JavaUtilIterator> iter = [((id<JavaLangIterable>) nil_chk(source)) iterator]; [((id<JavaUtilIterator>) nil_chk(iter)) hasNext]; ) {
    id val = [iter next];
    if (matcher == nil || [matcher matchWithId:val]) {
      [((id<RuKorincUtilsUtils_Apply>) nil_chk(action)) applyWithJavaUtilIterator:iter withId:val];
      if (breakOn != nil && [breakOn matchWithId:val]) {
        return;
      }
    }
  }
}

RuKorincUtilsUtils_SearchResult *RuKorincUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_ApplySearchResult_(JavaUtilArrayList *source, id<RuKorincUtilsUtils_Matcher> condition, id<RuKorincUtilsUtils_ApplySearchResult> ifFound) {
  RuKorincUtilsUtils_initialize();
  return RuKorincUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_ApplySearchResult_withRuKorincUtilsUtils_Action_(source, condition, ifFound, nil);
}

RuKorincUtilsUtils_SearchResult *RuKorincUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincUtilsUtils_Matcher_withRuKorincUtilsUtils_ApplySearchResult_withRuKorincUtilsUtils_Action_(JavaUtilArrayList *source, id<RuKorincUtilsUtils_Matcher> condition, id<RuKorincUtilsUtils_ApplySearchResult> ifFound, id<RuKorincUtilsUtils_Action> not_) {
  RuKorincUtilsUtils_initialize();
  RuKorincUtilsUtils_SearchResult *res = new_RuKorincUtilsUtils_SearchResult_initWithInt_withId_(-1, nil);
  jint position = -1;
  jboolean found = false;
  for (id __strong val in nil_chk(source)) {
    if ([((id<RuKorincUtilsUtils_Matcher>) nil_chk(condition)) matchWithId:val]) {
      res = new_RuKorincUtilsUtils_SearchResult_initWithInt_withId_(++position, val);
      found = true;
      break;
    }
    position++;
  }
  if (found) {
    if (ifFound != nil) {
      [ifFound applyWithRuKorincUtilsUtils_SearchResult:res];
    }
  }
  else {
    if (not_ != nil) {
      [not_ call];
    }
  }
  return res;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils)

@implementation RuKorincUtilsUtils_SearchResult

- (instancetype)initWithInt:(jint)position
                     withId:(id)item {
  RuKorincUtilsUtils_SearchResult_initWithInt_withId_(self, position, item);
  return self;
}

- (jint)getPosition {
  return position_;
}

- (id)getItem {
  return item_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithInt:withId:);
  methods[1].selector = @selector(getPosition);
  methods[2].selector = @selector(getItem);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "position_", "I", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "item_", "LNSObject;", .constantValue.asLong = 0, 0x12, -1, -1, 3, -1 },
  };
  static const void *ptrTable[] = { "ILNSObject;", "(ITT;)V", "()TT;", "TT;", "LRuKorincUtilsUtils;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils_SearchResult = { "SearchResult", "ru.korinc.utils", ptrTable, methods, fields, 7, 0x9, 3, 2, 4, -1, -1, 5, -1 };
  return &_RuKorincUtilsUtils_SearchResult;
}

@end

void RuKorincUtilsUtils_SearchResult_initWithInt_withId_(RuKorincUtilsUtils_SearchResult *self, jint position, id item) {
  NSObject_init(self);
  self->position_ = position;
  self->item_ = item;
}

RuKorincUtilsUtils_SearchResult *new_RuKorincUtilsUtils_SearchResult_initWithInt_withId_(jint position, id item) {
  J2OBJC_NEW_IMPL(RuKorincUtilsUtils_SearchResult, initWithInt_withId_, position, item)
}

RuKorincUtilsUtils_SearchResult *create_RuKorincUtilsUtils_SearchResult_initWithInt_withId_(jint position, id item) {
  J2OBJC_CREATE_IMPL(RuKorincUtilsUtils_SearchResult, initWithInt_withId_, position, item)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils_SearchResult)

@implementation RuKorincUtilsUtils_Matcher

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "Z", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(matchWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "match", "LNSObject;", "(TT;)Z", "LRuKorincUtilsUtils;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils_Matcher = { "Matcher", "ru.korinc.utils", ptrTable, methods, NULL, 7, 0x609, 1, 0, 3, -1, -1, 4, -1 };
  return &_RuKorincUtilsUtils_Matcher;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils_Matcher)

@implementation RuKorincUtilsUtils_ApplySearchResult

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(applyWithRuKorincUtilsUtils_SearchResult:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "apply", "LRuKorincUtilsUtils_SearchResult;", "(Lru/korinc/utils/Utils$SearchResult<TT;>;)V", "LRuKorincUtilsUtils;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils_ApplySearchResult = { "ApplySearchResult", "ru.korinc.utils", ptrTable, methods, NULL, 7, 0x609, 1, 0, 3, -1, -1, 4, -1 };
  return &_RuKorincUtilsUtils_ApplySearchResult;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils_ApplySearchResult)

@implementation RuKorincUtilsUtils_Apply

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, 2, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(applyWithJavaUtilIterator:withId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "apply", "LJavaUtilIterator;LNSObject;", "(Ljava/util/Iterator<TT;>;TT;)V", "LRuKorincUtilsUtils;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils_Apply = { "Apply", "ru.korinc.utils", ptrTable, methods, NULL, 7, 0x609, 1, 0, 3, -1, -1, 4, -1 };
  return &_RuKorincUtilsUtils_Apply;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils_Apply)

@implementation RuKorincUtilsUtils_Action

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(call);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LRuKorincUtilsUtils;" };
  static const J2ObjcClassInfo _RuKorincUtilsUtils_Action = { "Action", "ru.korinc.utils", ptrTable, methods, NULL, 7, 0x609, 1, 0, 0, -1, -1, -1, -1 };
  return &_RuKorincUtilsUtils_Action;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RuKorincUtilsUtils_Action)
