//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/ru/korinc/core/utils/Utils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Utils")
#ifdef RESTRICT_Utils
#define INCLUDE_ALL_Utils 0
#else
#define INCLUDE_ALL_Utils 1
#endif
#undef RESTRICT_Utils

#if !defined (RuKorincCoreUtilsUtils_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils))
#define RuKorincCoreUtilsUtils_

@class JavaUtilArrayList;
@class RuKorincCoreUtilsUtils_SearchResult;
@protocol JavaLangIterable;
@protocol RuKorincCoreUtilsUtils_Action;
@protocol RuKorincCoreUtilsUtils_Apply;
@protocol RuKorincCoreUtilsUtils_ApplySearchResult;
@protocol RuKorincCoreUtilsUtils_Matcher;

@interface RuKorincCoreUtilsUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
 withRuKorincCoreUtilsUtils_Apply:(id<RuKorincCoreUtilsUtils_Apply>)action;

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
withRuKorincCoreUtilsUtils_Matcher:(id<RuKorincCoreUtilsUtils_Matcher>)matcher
 withRuKorincCoreUtilsUtils_Apply:(id<RuKorincCoreUtilsUtils_Apply>)action;

+ (void)applyWithJavaLangIterable:(id<JavaLangIterable>)source
withRuKorincCoreUtilsUtils_Matcher:(id<RuKorincCoreUtilsUtils_Matcher>)matcher
withRuKorincCoreUtilsUtils_Matcher:(id<RuKorincCoreUtilsUtils_Matcher>)breakOn
 withRuKorincCoreUtilsUtils_Apply:(id<RuKorincCoreUtilsUtils_Apply>)action;

+ (RuKorincCoreUtilsUtils_SearchResult *)arrayListFirstWithJavaUtilArrayList:(JavaUtilArrayList *)source
                                          withRuKorincCoreUtilsUtils_Matcher:(id<RuKorincCoreUtilsUtils_Matcher>)condition
                                withRuKorincCoreUtilsUtils_ApplySearchResult:(id<RuKorincCoreUtilsUtils_ApplySearchResult>)ifFound;

+ (RuKorincCoreUtilsUtils_SearchResult *)arrayListFirstWithJavaUtilArrayList:(JavaUtilArrayList *)source
                                          withRuKorincCoreUtilsUtils_Matcher:(id<RuKorincCoreUtilsUtils_Matcher>)condition
                                withRuKorincCoreUtilsUtils_ApplySearchResult:(id<RuKorincCoreUtilsUtils_ApplySearchResult>)ifFound
                                           withRuKorincCoreUtilsUtils_Action:(id<RuKorincCoreUtilsUtils_Action>)not_;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils)

FOUNDATION_EXPORT void RuKorincCoreUtilsUtils_init(RuKorincCoreUtilsUtils *self);

FOUNDATION_EXPORT RuKorincCoreUtilsUtils *new_RuKorincCoreUtilsUtils_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreUtilsUtils *create_RuKorincCoreUtilsUtils_init();

FOUNDATION_EXPORT void RuKorincCoreUtilsUtils_applyWithJavaLangIterable_withRuKorincCoreUtilsUtils_Matcher_withRuKorincCoreUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincCoreUtilsUtils_Matcher> matcher, id<RuKorincCoreUtilsUtils_Apply> action);

FOUNDATION_EXPORT void RuKorincCoreUtilsUtils_applyWithJavaLangIterable_withRuKorincCoreUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincCoreUtilsUtils_Apply> action);

FOUNDATION_EXPORT void RuKorincCoreUtilsUtils_applyWithJavaLangIterable_withRuKorincCoreUtilsUtils_Matcher_withRuKorincCoreUtilsUtils_Matcher_withRuKorincCoreUtilsUtils_Apply_(id<JavaLangIterable> source, id<RuKorincCoreUtilsUtils_Matcher> matcher, id<RuKorincCoreUtilsUtils_Matcher> breakOn, id<RuKorincCoreUtilsUtils_Apply> action);

FOUNDATION_EXPORT RuKorincCoreUtilsUtils_SearchResult *RuKorincCoreUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincCoreUtilsUtils_Matcher_withRuKorincCoreUtilsUtils_ApplySearchResult_(JavaUtilArrayList *source, id<RuKorincCoreUtilsUtils_Matcher> condition, id<RuKorincCoreUtilsUtils_ApplySearchResult> ifFound);

FOUNDATION_EXPORT RuKorincCoreUtilsUtils_SearchResult *RuKorincCoreUtilsUtils_arrayListFirstWithJavaUtilArrayList_withRuKorincCoreUtilsUtils_Matcher_withRuKorincCoreUtilsUtils_ApplySearchResult_withRuKorincCoreUtilsUtils_Action_(JavaUtilArrayList *source, id<RuKorincCoreUtilsUtils_Matcher> condition, id<RuKorincCoreUtilsUtils_ApplySearchResult> ifFound, id<RuKorincCoreUtilsUtils_Action> not_);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils)

#endif

#if !defined (RuKorincCoreUtilsUtils_SearchResult_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils_SearchResult))
#define RuKorincCoreUtilsUtils_SearchResult_

@interface RuKorincCoreUtilsUtils_SearchResult : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)position
                     withId:(id)item;

- (id)getItem;

- (jint)getPosition;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils_SearchResult)

FOUNDATION_EXPORT void RuKorincCoreUtilsUtils_SearchResult_initWithInt_withId_(RuKorincCoreUtilsUtils_SearchResult *self, jint position, id item);

FOUNDATION_EXPORT RuKorincCoreUtilsUtils_SearchResult *new_RuKorincCoreUtilsUtils_SearchResult_initWithInt_withId_(jint position, id item) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT RuKorincCoreUtilsUtils_SearchResult *create_RuKorincCoreUtilsUtils_SearchResult_initWithInt_withId_(jint position, id item);

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils_SearchResult)

#endif

#if !defined (RuKorincCoreUtilsUtils_Matcher_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils_Matcher))
#define RuKorincCoreUtilsUtils_Matcher_

@protocol RuKorincCoreUtilsUtils_Matcher < JavaObject >

- (jboolean)matchWithId:(id)val;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils_Matcher)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils_Matcher)

#endif

#if !defined (RuKorincCoreUtilsUtils_ApplySearchResult_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils_ApplySearchResult))
#define RuKorincCoreUtilsUtils_ApplySearchResult_

@class RuKorincCoreUtilsUtils_SearchResult;

@protocol RuKorincCoreUtilsUtils_ApplySearchResult < JavaObject >

- (void)applyWithRuKorincCoreUtilsUtils_SearchResult:(RuKorincCoreUtilsUtils_SearchResult *)val;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils_ApplySearchResult)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils_ApplySearchResult)

#endif

#if !defined (RuKorincCoreUtilsUtils_Apply_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils_Apply))
#define RuKorincCoreUtilsUtils_Apply_

@protocol JavaUtilIterator;

@protocol RuKorincCoreUtilsUtils_Apply < JavaObject >

- (void)applyWithJavaUtilIterator:(id<JavaUtilIterator>)iterator
                           withId:(id)val;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils_Apply)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils_Apply)

#endif

#if !defined (RuKorincCoreUtilsUtils_Action_) && (INCLUDE_ALL_Utils || defined(INCLUDE_RuKorincCoreUtilsUtils_Action))
#define RuKorincCoreUtilsUtils_Action_

@protocol RuKorincCoreUtilsUtils_Action < JavaObject >

- (void)call;

@end

J2OBJC_EMPTY_STATIC_INIT(RuKorincCoreUtilsUtils_Action)

J2OBJC_TYPE_LITERAL_HEADER(RuKorincCoreUtilsUtils_Action)

#endif

#pragma pop_macro("INCLUDE_ALL_Utils")
