//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/Weak.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "Weak.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@interface GoogleJ2objcAnnotationsWeak : NSObject

@end

__attribute__((unused)) static IOSObjectArray *GoogleJ2objcAnnotationsWeak__Annotations$0();

@implementation GoogleJ2objcAnnotationsWeak

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { (void *)&GoogleJ2objcAnnotationsWeak__Annotations$0 };
  static const J2ObjcClassInfo _GoogleJ2objcAnnotationsWeak = { "Weak", "google.j2objc.annotations", ptrTable, NULL, NULL, 7, 0x2609, 0, 0, -1, -1, -1, -1, 0 };
  return &_GoogleJ2objcAnnotationsWeak;
}

@end

IOSObjectArray *GoogleJ2objcAnnotationsWeak__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, FIELD), JreLoadEnum(JavaLangAnnotationElementType, LOCAL_VARIABLE), JreLoadEnum(JavaLangAnnotationElementType, PARAMETER) } count:3 type:JavaLangAnnotationElementType_class_()]), create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, CLASS)) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GoogleJ2objcAnnotationsWeak)
