//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../core/src/main/java/google/j2objc/annotations/Weak.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Weak")
#ifdef RESTRICT_Weak
#define INCLUDE_ALL_Weak 0
#else
#define INCLUDE_ALL_Weak 1
#endif
#undef RESTRICT_Weak

#if !defined (GoogleJ2objcAnnotationsWeak_) && (INCLUDE_ALL_Weak || defined(INCLUDE_GoogleJ2objcAnnotationsWeak))
#define GoogleJ2objcAnnotationsWeak_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol GoogleJ2objcAnnotationsWeak < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(GoogleJ2objcAnnotationsWeak)

J2OBJC_TYPE_LITERAL_HEADER(GoogleJ2objcAnnotationsWeak)

#endif

#pragma pop_macro("INCLUDE_ALL_Weak")
